#!/bin/bash -e

# verify commit message presence
if [ -z "$1" ]; then
  echo "usage:  sh gitty \"commit message\""
  exit
fi

# verify commit message format
if [ ! -z "$2" ]; then
  echo "usage: sh gitty \"commit message *in double quotes*\""
  exit
fi

# stage important project files
git add src/* resources/* README.md TODO unreplicated_bugs gitty .gitignore
# stage file deletions
git add -u .
# show user what's to be committed
git status
# commit with the message
git commit -m "$1"
# remind user of amend
echo "**if something isn't right, remember \"git commit --amend\"**"
